contact_links:
  - name: Are you looking for documentation on book-of-abstracts?
    url: https://digihistch24.github.io/book-of-abstracts
    about: Please see the documentation for book-of-abstracts on its GitHub Pages page.
  - name: Do want to discuss book-of-abstracts with the community?
    url: https://github.com/digihistch24/digihistch24.github.io/discussions
    about: Please see the discussions page for book-of-abstracts.
blank_issues_enabled: true
